/**
 * src/abis/unyToken.ts
 * Minimal ABI for UNYToken (ERC-20 + Ownable).
 * Full ABI auto-generated by Hardhat after compilation; this covers UI reads.
 */

export const UNY_TOKEN_ABI = [
  // ERC-20 read
  { name: "name",        type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { name: "symbol",      type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { name: "decimals",    type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint8"  }] },
  { name: "totalSupply", type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "uint256"}] },
  {
    name: "balanceOf",   type: "function", stateMutability: "view",
    inputs:  [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "allowance",   type: "function", stateMutability: "view",
    inputs:  [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  // ERC-20 write
  {
    name: "transfer",    type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    name: "approve",     type: "function", stateMutability: "nonpayable",
    inputs:  [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  // Events
  {
    name: "Transfer",    type: "event",
    inputs: [
      { name: "from",  type: "address", indexed: true  },
      { name: "to",    type: "address", indexed: true  },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Approval",    type: "event",
    inputs: [
      { name: "owner",   type: "address", indexed: true  },
      { name: "spender", type: "address", indexed: true  },
      { name: "value",   type: "uint256", indexed: false },
    ],
  },
  // Ownable
  { name: "owner",              type: "function", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    name: "transferOwnership",  type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }], outputs: [],
  },
] as const;
